[package]
name = "either_field"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
# make sure to not use extra-traits in published versions
syn = {version = "2.0.100", features = ["parsing","derive","extra-traits"]}
